include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: false
    prefer_double_quotes: true
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    omit_local_variable_types: false
