name: htmleez
description: HTML easy. A lightweight library for creating HTML programmatically in Dart.
version: 0.13.0
repository: https://github.com/namzug16/htmdart/tree/master/packages/htmleez
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0

topics:
  - html
