name: htmleez
description: HTML easy. A lightweight library for creating HTML programmatically in Dart.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
