name: htmleez
description: HTML easy. A lightweight library for creating HTML programmatically in Dart.
version: 0.1.12
repository: https://github.com/namzug16/htmdart/tree/master/packages/htmleez

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

topics:
  - html
