name: htmdart
description: Build simple systems with Dart + HTMX
version: 0.0.13
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  htmleez: ^0.1.10
  shelf: ^1.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
