name: htmdart
description: Build simple systems with Dart + HTMX
version: 0.0.15
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  htmleez: ^0.1.11
  http_parser: ^4.1.2
  mime: ^2.0.0
  shelf: ^1.4.2
  stack_trace: ^1.12.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
