name: htmdart
description: Build simple systems with Dart + HTMX
version: 0.6.1
repository: https://github.com/namzug16/htmdart/tree/master/packages/htmdart

environment:
  sdk: ^3.5.0

dependencies:
  htmleez: ^0.11.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0

topics:
  - server
  - htmx
