name: htmdart
description: Build simple systems with Dart + HTMX
version: 0.0.7
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  htmleez: ^0.1.5
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
