name: htmdart
description: Build fast, hypermedia-driven web apps with Dart + HTMX
version: 0.8.0
repository: https://github.com/namzug16/htmdart
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  htmleez: ^0.13.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^7.0.0

topics:
  - server
  - netto
  - htmx
