name: htmdart
description: Build simple systems with Dart + HTMX
version: 0.7.2
repository: https://github.com/namzug16/htmdart

environment:
  sdk: ^3.8.0

dependencies:
  htmleez: ^0.12.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  shelf: ^1.4.2
  shelf_hotreload: ^1.5.0
  stack_trace: ^1.12.1

dev_dependencies:
  http: ^1.5.0
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0

topics:
  - server
  - htmx
