name: todo
description: Todo app built with HTMDART
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  netto: ^0.1.0
  args: ^2.4.0
  htmdart: ^0.7.0
  dart_mappable: ^4.3.0
  sqlite3: ^2.7.2

dev_dependencies:
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
