name: htmdart_site
description: A server app using shelf and HTMDART.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.3
  htmdart: ^0.0.2
  markdown: ^7.2.2
  html: ^0.15.5

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
